name: Daily Calendar-Notion Sync

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2:00 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client notion-client pandas python-dotenv supabase

    - name: Run fetch_google_calendar_data.py
      id: fetch_data
      run: |
        python fetch_google_calendar_data.py 2>&1 | tee output.log
      continue-on-error: true

    - name: Check for errors in fetch_google_calendar_data.py
      id: check_errors
      run: |
        if grep -q "Traceback" output.log; then
          echo "Error occurred in script execution:"
          cat output.log
          echo "Python version:"
          python --version
          echo "Installed packages:"
          pip list
          echo "Script contents:"
          cat fetch_google_calendar_data.py
          exit 1
        else
          echo "fetch_google_calendar_data.py executed successfully"
          cat output.log
        fi

    - name: Run prepare_data_for_supabase.py
      id: prepare_data
      if: steps.check_errors.outcome == 'success'
      run: python prepare_data_for_supabase.py

    - name: Run database.py
      id: update_database
      if: steps.prepare_data.outcome == 'success'
      run: python database.py
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}

    - name: List directory contents
      if: failure()
      run: |
        echo "Contents of the current directory:"
        ls -la

    - name: Commit and push if changed
      if: success()
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update chart data" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
