name: Daily Calendar-Notion Sync

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2:00 AM UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client notion-client pandas supabase

    - name: Run fetch_google_calendar_data.py
      run: |
        python fetch_google_calendar_data.py 2>&1 | tee output_fetch.log
      continue-on-error: true

    - name: Run prepare_data_for_supabase.py
      run: |
        python prepare_data_for_supabase.py 2>&1 | tee output_prepare.log
      continue-on-error: true

    - name: Run database.py
      run: |
        python database.py 2>&1 | tee output_database.log
      continue-on-error: true

    - name: Check for errors
      run: |
        if grep -q "Traceback" output_fetch.log output_prepare.log output_database.log; then
          echo "Error occurred in script execution:"
          cat output_fetch.log output_prepare.log output_database.log
          echo "Python version:"
          python --version
          echo "Installed packages:"
          pip list
          echo "Script contents:"
          cat fetch_google_calendar_data.py prepare_data_for_supabase.py database.py
          exit 1
        else
          echo "All scripts executed successfully"
          cat output_fetch.log output_prepare.log output_database.log
        fi

    - name: List directory contents
      if: failure()
      run: |
        echo "Contents of the current directory:"
        ls -la

    - name: Commit and push if changed
      if: success()
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update chart data and sync with Supabase" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
